import { useCallback } from "react";
import { ArrowDownTrayIcon, DocumentTextIcon } from "@heroicons/react/24/outline";
import CopyButton from "../components/CopyButton.jsx";
import { downloadTextFile } from "../lib/download.js";

/**
 * Download rows for a /cert response: the RadSec private key, client
 * certificate, and CA chain — same filenames the helium-wallet CLI writes
 * (<name>.pk / <name>.cer / data-only.ca). Per-file buttons are the primary
 * UI; a sequential "download all" would trip Chrome's multiple-download
 * blocker, so there deliberately isn't one.
 *
 * The response also carries the location record (`nas_ids`, `location_address`)
 * the cert was issued for — the NAS ID isn't on-chain for a converted network
 * (mobile_info.deployment_info is None), so this is where an operator reads it
 * back on the Manage tab.
 */
export default function CertDownloads({ cert, baseName }) {
  const name = (baseName || "hotspot").toLowerCase().replace(/[^a-z0-9-]+/g, "-");

  const nasIds = cert.nas_ids || [];
  const locationAddress = cert.location_address || "";

  const files = [
    { filename: `${name}.pk`, label: "Private key", content: cert.radsec_private_key, note: "Keep this file private" },
    { filename: `${name}.cer`, label: "Client certificate", content: cert.radsec_certificate, note: null },
    { filename: "data-only.ca", label: "CA chain", content: cert.radsec_ca_chain, note: null },
  ];

  const handleDownload = useCallback((file) => {
    downloadTextFile(file.filename, file.content, "application/x-pem-file");
  }, []);

  const expires = cert.radsec_cert_expire ? new Date(cert.radsec_cert_expire) : null;

  return (
    <div className="space-y-3">
      {(nasIds.length > 0 || locationAddress) && (
        <div className="rounded-lg bg-surface-inset px-3 py-1.5">
          {nasIds.map((id) => (
            <div key={id} className="flex items-center justify-between gap-3 py-1.5">
              <span className="text-xs text-content-secondary">NAS ID</span>
              <span className="flex min-w-0 items-center gap-1.5">
                <span className="truncate font-mono text-xs text-content">{id}</span>
                <CopyButton text={id} size="h-3.5 w-3.5" />
              </span>
            </div>
          ))}
          {locationAddress && (
            <div className="flex items-start justify-between gap-3 py-1.5">
              <span className="shrink-0 text-xs text-content-secondary">Address</span>
              <span className="min-w-0 text-right text-xs text-content">{locationAddress}</span>
            </div>
          )}
        </div>
      )}

      <ul className="divide-y divide-border overflow-hidden rounded-lg bg-surface-inset">
        {files.map((file) => (
          <li key={file.filename} className="flex items-center gap-3 px-3 py-2.5">
            <DocumentTextIcon className="h-4 w-4 shrink-0 text-content-tertiary" />
            <div className="min-w-0 flex-1">
              <div className="truncate font-mono text-xs text-content">{file.filename}</div>
              <div className="text-[11px] text-content-tertiary">
                {file.label}
                {file.note ? <span className="text-amber-600 dark:text-amber-400"> · {file.note}</span> : null}
              </div>
            </div>
            <button
              type="button"
              onClick={() => handleDownload(file)}
              className="inline-flex shrink-0 items-center gap-1.5 rounded-lg border border-border px-2.5 py-1.5 text-xs font-medium text-content hover:bg-surface-raised"
            >
              <ArrowDownTrayIcon className="h-3.5 w-3.5" /> Download
            </button>
          </li>
        ))}
      </ul>

      {expires && !isNaN(expires) && (
        <p className="text-xs text-content-tertiary">
          Certificate valid until {expires.toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" })}.
        </p>
      )}

      <p className="text-xs text-content-tertiary">
        These files are generated by the Helium certificate service and relayed to your browser
        through heliumtools, which never stores or logs your certificates or keys. Keep the
        private key (.pk) file safe, and re-download these certificates any time from the Manage tab
        by signing with the wallet that owns this Hotspot.
      </p>
    </div>
  );
}
